public class ArrayDequeTest {
    public static void main(String[] args) {
        ArrayDeque<Number> L = new ArrayDeque<>();
        String curr = " ";
        boolean isEmp = L.isEmpty();
        int length = L.size();
       /* L.addFirst("1991");
        L.addFirst("1992");
        L.addFirst("1993");
        L.addFirst("2020");
        L.addFirst("2019");
        L.addFirst("2018");
        L.addFirst("2017");
        L.addFirst("2016");
        L.addFirst("2015");
        L.addFirst("2014");
        L.addFirst("2013");
        L.addFirst("2012");
        L.addFirst("2011");
        L.addFirst("2010");
        L.addFirst("2009");
        L.addFirst("2008");
        L.addFirst("2007");
        L.addFirst("2006");
        L.addFirst("2005");
        isEmp = L.isEmpty();
        length = L.size();
        L.printDeque();
        curr = L.removeFirst();
        curr = L.removeLast();
        curr = L.removeFirst();
        curr = L.removeFirst();
        curr = L.removeLast();
        curr = L.removeFirst();
        curr = L.removeFirst();
        curr = L.removeLast();
        curr = L.removeFirst();
        curr = L.removeFirst();
        curr = L.removeLast();
        curr = L.removeFirst();
        curr = L.removeFirst();
        curr = L.removeLast();
        curr = L.removeFirst();
       curr = L.removeLast();
        curr = L.removeFirst();

        curr = L.removeLast();
        curr = L.removeLast();
        curr = L.removeLast();
        curr = L.removeLast();
        curr = L.removeLast();
        curr = L.removeLast();
        curr = L.removeLast();
        curr = L.removeLast();
        curr = L.removeLast();
        curr = L.removeLast();
        curr = L.removeLast();
        curr = L.removeLast();
        curr = L.removeLast();
        curr = L.removeLast();
        curr = L.removeLast();
        curr = L.removeLast();
        curr = L.removeLast();
        curr = L.removeLast();
        curr = L.removeLast();
        curr = L.removeLast();
        curr = L.removeLast();
        curr = L.removeLast();
        curr = L.removeLast();
        curr = L.removeLast();
        curr = L.removeLast();
        curr = L.removeLast();
        L.addFirst("1991");
        L.addFirst("1992");
        L.addFirst("1993");
        L.addFirst("2020");
        L.addFirst("2019");
        L.addFirst("2018");
        L.addFirst("2017");
        L.addFirst("2016");
        L.addFirst("2015");
        L.addFirst("2014");
        L.addFirst("2013");
        L.addFirst("2012");
        L.addFirst("2011");
        L.addFirst("2010");
        L.addFirst("2009");
        L.addFirst("2008");
        L.addFirst("2007");
        L.addFirst("2006");
        L.addFirst("2005");
        curr = L.get(4);*/
        L.addFirst(0);
        L.removeLast();
        L.addFirst(2);
        L.removeLast();
        L.addLast(4);
        L.addLast(5);
        L.addLast(6);
        L.addFirst(7);
        L.addLast(8);
        L.addLast(9);
        L.removeFirst();
        L.removeFirst();
        L.addLast(12);
    }
}
